googleAnalytics = "G-4TKP0K59Z3"

baseURL = 'https://ritarka.github.io/'
languageCode = 'en-us'
title = 'Ritarka Samanta'
enableEmoji = true
theme = ["hugo-embed-pdf-shortcode", 'hugo-book']
enableInlineShortcodes = true

# sectionPagesMenu = 'main'

enableGitInfo = true

[params]
  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle = '/menu'

  # # (Optional, default docs) Specify root page to render child pages as menu.
  # # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection = 'docs'

  BookTheme = 'light'




[markup.goldmark.renderer]
  unsafe = true

[menu]

[[menu.after]]
  name = "Mail"
  url = "mailto:ritarkasamanta@gmail.com"
  weight = 5


[[menu.after]]
  name = "Github"
  url = "https://github.com/Ritarka"
  weight = 10

[[menu.after]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/ritarka/"
  weight = 20
