baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ritarka Samanta'
enableEmoji = true
theme = ["hugo-embed-pdf-shortcode", 'hugo-book']
enableInlineShortcodes = true

[markup.goldmark.renderer]
  unsafe = true

[menu]
# [[menu.before]]

[[menu.after]]
  name = "Mail"
  url = "mailto:ritarka.samanta@gmail.com"
  weight = 5


[[menu.after]]
  name = "Github"
  url = "https://github.com/Ritarka"
  weight = 10

[[menu.after]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/ritarka/"
  weight = 20
