baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ritarka Samanta'

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Ritarka"
  weight = 10

[[menu.after]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/ritarka/"
  weight = 20
