googleAnalytics = "G-4TKP0K59Z3"

baseURL = 'https://ritarka.github.io/'
languageCode = 'en-us'
title = 'Ritarka Samanta'
enableEmoji = true
theme = ["hugo-embed-pdf-shortcode", 'hugo-book']
enableInlineShortcodes = true
sectionPagesMenu = 'main'
enableGitInfo = true


[markup.goldmark.renderer]
  unsafe = true

[menu]

# [[menus]]
#   name = 'Resume'
#   pageRef = '/resume'
#   weight = 20


[[menu.after]]
  name = "Mail"
  url = "mailto:ritarka.samanta@gmail.com"
  weight = 5


[[menu.after]]
  name = "Github"
  url = "https://github.com/Ritarka"
  weight = 10

[[menu.after]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/ritarka/"
  weight = 20
